---
- name: intalling weblayer
  hosts: web
  user: root
  become: yes 

  tasks:
  - name: install apache
    yum:
    name: httpd
    state: present
  - name: install unzip
    yum:
      name: unzip
      state: present
  - name: start apache
    service:
     name: httpd
     state: started
      
      
